export interface GalleryItem {
  id: number;
  title: string;
  category: 'Exhibitions & Shows' | 'Global Delegations' | 'Heritage & Founders';
  image: string;
  filename: string;
  description: string;
}

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    title: "Founder at Cultural Heritage Site",
    category: "Heritage & Founders",
    filename: "WhatsApp Image 2026-08-11 at 21.01.47.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.47.jpeg",
    description: "Founder visiting traditional architectural heritage during an international trade mission.",
  },
  {
    id: 2,
    title: "FACETS International Exhibition Wall",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.48.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.48.jpeg",
    description: "Director standing at the FACETS Sri Lanka International Gem & Jewellery Show pavilion.",
  },
  {
    id: 3,
    title: "FACETS Sri Lanka Gem Show",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.48 (1).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.48 (1).jpeg",
    description: "The Choice team members at the FACETS Sri Lanka International Gem & Jewellery Show.",
  },
  {
    id: 4,
    title: "Gem Sri Lanka Celebration",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.48 (2).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.48 (2).jpeg",
    description: "Director at the CGJTA \"GEM SRI LANKA - A Celebration of Gemstones\" event backdrop.",
  },
  {
    id: 5,
    title: "European Trade Mission (Germany)",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.48 (3).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.48 (3).jpeg",
    description: "Director on location during a gemstone sourcing and client visiting trip in Germany.",
  },
  {
    id: 6,
    title: "Master Gemologist Desk Consultation",
    category: "Heritage & Founders",
    filename: "WhatsApp Image 2026-08-11 at 21.01.48 (4).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.48 (4).jpeg",
    description: "Senior founder & master gemologist evaluating rare gemstone parcels at the executive desk.",
  },
  {
    id: 7,
    title: "Star Sapphires Trade Exhibition",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.49.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.49.jpeg",
    description: "Specialized booth featuring natural Ceylon Star Sapphires and rare faceted stones.",
  },
  {
    id: 8,
    title: "The Choice Gem Showcase Booth",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.49 (1).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.49 (1).jpeg",
    description: "Directors presenting Ceylon gemstone trays inside our custom exhibition booth.",
  },
  {
    id: 9,
    title: "Munich Gem World Entrance",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.49 (2).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.49 (2).jpeg",
    description: "The Choice delegation arriving at the Munich Gem World Mineralientage in Germany.",
  },
  {
    id: 10,
    title: "GIA Certified Gem Display Desk",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.49 (3).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.49 (3).jpeg",
    description: "Director showcasing GIA certified sapphires and multi-colored gemstone suites.",
  },
  {
    id: 11,
    title: "Official Gem Symposium Handshake",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.50.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.50.jpeg",
    description: "Director receiving recognition at an official international gemology trade ceremony.",
  },
  {
    id: 12,
    title: "Classic Trade Show Exhibition Hall",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.50 (1).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.50 (1).jpeg",
    description: "Historical trade fair pavilion presenting Ceylon sapphires to global media and buyers.",
  },
  {
    id: 13,
    title: "Executive Founders at Glass Counter",
    category: "Heritage & Founders",
    filename: "WhatsApp Image 2026-08-11 at 21.01.50 (2).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.50 (2).jpeg",
    description: "Executive founders and directors of The Choice behind the gem showcase counter.",
  },
  {
    id: 14,
    title: "International Client Consultation",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.50 (3).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.50 (3).jpeg",
    description: "Senior founders interacting with international buyers at exhibition booth 5.1C1-01.",
  },
  {
    id: 15,
    title: "Gem Vault & Trading Office",
    category: "Heritage & Founders",
    filename: "WhatsApp Image 2026-08-11 at 21.01.51.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.51.jpeg",
    description: "Top-down view of our central office and gem vault where stones are sorted and authenticated.",
  },
  {
    id: 16,
    title: "High-Traffic Exhibition Sales Counter",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.51 (1).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.51 (1).jpeg",
    description: "Trade show booth buzzing with visitors examining precious stone collections.",
  },
  {
    id: 17,
    title: "VIP Buyer Consultation at Stand 028",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.51 (2).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.51 (2).jpeg",
    description: "Meeting corporate delegates and high-net-worth buyers at booth 028.",
  },
  {
    id: 18,
    title: "Founder at Golden Monument",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.51 (3).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.51 (3).jpeg",
    description: "Senior founder seated in front of a landmark sculpture during an international expo trip.",
  },
  {
    id: 19,
    title: "China Trade Tour Landmark Visit",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.52.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.52.jpeg",
    description: "Senior founder standing at architectural site during a Chinese gemstone trade mission.",
  },
  {
    id: 20,
    title: "Trade Mission Departure",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.52 (1).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.52 (1).jpeg",
    description: "Director prepared with travel gear for an overseas gem trade exhibition.",
  },
  {
    id: 21,
    title: "China Kunming International Stone Expo",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.52 (2).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.52 (2).jpeg",
    description: "The Choice delegation team at China Kunming International Stone Expo booth 1562.",
  },
  {
    id: 22,
    title: "Commonwealth Business Forum (London)",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.52 (3).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.52 (3).jpeg",
    description: "Senior founder attending the Commonwealth Business Forum at Guildhall Art Gallery in London.",
  },
  {
    id: 23,
    title: "London Guildhall Trade Delegation",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.53.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.53.jpeg",
    description: "Senior founder representing Ceylon gem trade at Guildhall, London.",
  },
  {
    id: 24,
    title: "International Business Dinner",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.53 (1).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.53 (1).jpeg",
    description: "Founders sharing a celebratory meal with global gemstone trade partners.",
  },
  {
    id: 25,
    title: "Senior Founder at Trade Counter",
    category: "Heritage & Founders",
    filename: "WhatsApp Image 2026-08-11 at 21.01.53 (2).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.53 (2).jpeg",
    description: "Senior founder and director managing gemstone inspections at exhibition booth.",
  },
  {
    id: 26,
    title: "Flight to Global Trade Expo",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.53 (3).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.53 (3).jpeg",
    description: "Directors en route to an international gemstone exhibition in Asia.",
  },
  {
    id: 27,
    title: "Sri Lanka Sapphire Capital Showcase",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.54.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.54.jpeg",
    description: "Senior founder promoting \"Sri Lanka - The Sapphire Capital of the World\" in China.",
  },
  {
    id: 28,
    title: "Interactive Gemstone Demonstration",
    category: "Exhibitions & Shows",
    filename: "WhatsApp Image 2026-08-11 at 21.01.54 (1).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.54 (1).jpeg",
    description: "Demonstrating sapphire light reflection and cut quality to trade visitors.",
  },
  {
    id: 29,
    title: "Trade Partner Gala Dinner",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.54 (2).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.54 (2).jpeg",
    description: "The Choice executive board dining with international gemstone industry leaders.",
  },
  {
    id: 30,
    title: "International Travel Transit",
    category: "Global Delegations",
    filename: "WhatsApp Image 2026-08-11 at 21.01.54 (3).jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.54 (3).jpeg",
    description: "Senior founder traveling between trade shows with secure gemstone transport cases.",
  },
  {
    id: 31,
    title: "Executive Board at Illuminated Display",
    category: "Heritage & Founders",
    filename: "WhatsApp Image 2026-08-11 at 21.01.55.jpeg",
    image: "/WhatsApp Image 2026-08-11 at 21.01.55.jpeg",
    description: "Executive directors presenting our flagship gemstone collection at an international showcase.",
  },
];
