export interface GalleryItem {
  id: number;
  title: string;
  category: 'Exhibitions' | 'Gemstones' | 'Jewelry';
  location?: string;
  year?: string;
  image: string;
  description?: string;
}

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    title: 'Ceylon Blue Sapphire Showcase',
    category: 'Gemstones',
    location: 'Colombo, Sri Lanka',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.47.jpeg',
    description: 'Exquisite natural unheated Ceylon blue sapphire displaying vivid saturation and clarity.',
  },
  {
    id: 2,
    title: 'Tucson Gem & Mineral Show',
    category: 'Exhibitions',
    location: 'Arizona, USA',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.48 (1).jpeg',
    description: 'High-end showcase booth at the annual Tucson Gem Fair.',
  },
  {
    id: 3,
    title: 'Handcrafted Diamond & Gem Ring',
    category: 'Jewelry',
    location: 'Private Collection',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.48 (2).jpeg',
    description: 'Bespoke fine jewelry ring crafted with precision platinum setting.',
  },
  {
    id: 4,
    title: 'Rare Padparadscha Sapphire',
    category: 'Gemstones',
    location: 'Ratnapura Mines',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.48 (3).jpeg',
    description: 'A prized lotus-colored Padparadscha sapphire certified by international gemological labs.',
  },
  {
    id: 5,
    title: 'Hong Kong Jewellery & Gem Fair',
    category: 'Exhibitions',
    location: 'Hong Kong Exhibition Centre',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.48 (4).jpeg',
    description: 'Exhibiting rare Ceylon gemstones to global trade buyers.',
  },
  {
    id: 6,
    title: 'Royal Yellow Sapphire',
    category: 'Gemstones',
    location: 'Sri Lanka',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.48.jpeg',
    description: 'Brilliant canary yellow sapphire cut in an elegant cushion style.',
  },
  {
    id: 7,
    title: 'High Jewelry Earrings Selection',
    category: 'Jewelry',
    location: 'Atelier Showcase',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.49 (1).jpeg',
    description: 'Fine drop earrings set with matched sapphire pairs and brilliant-cut diamonds.',
  },
  {
    id: 8,
    title: 'Facets Sri Lanka International',
    category: 'Exhibitions',
    location: 'BMICH, Colombo',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.49 (2).jpeg',
    description: 'Featured gallery pavilion highlighting top Ceylon origin gems.',
  },
  {
    id: 9,
    title: 'Precision Gem Faceting',
    category: 'Gemstones',
    location: 'Master Cutting Studio',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.49 (3).jpeg',
    description: 'Master lapidary shaping and polishing gemstone facets to perfection.',
  },
  {
    id: 10,
    title: 'Vicenzaoro Gold & Gem Fair',
    category: 'Exhibitions',
    location: 'Vicenza, Italy',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.49.jpeg',
    description: 'European exhibition featuring curated luxury gemstone collections.',
  },
  {
    id: 11,
    title: 'Ruby & Diamond Statement Necklace',
    category: 'Jewelry',
    location: 'Custom Order',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.50 (1).jpeg',
    description: 'Masterpiece necklace highlighting vivid pigeon-blood ruby centers.',
  },
  {
    id: 12,
    title: 'Uncut Rough Gem Crystal',
    category: 'Gemstones',
    location: 'Gem Fields',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.50 (2).jpeg',
    description: 'Ethically sourced natural rough sapphire crystal in pristine octahedral form.',
  },
  {
    id: 13,
    title: 'Bangkok International Gem Show',
    category: 'Exhibitions',
    location: 'Bangkok, Thailand',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.50 (3).jpeg',
    description: 'Participating in Asia’s premier gemstone trading expo.',
  },
  {
    id: 14,
    title: 'Royal Blue Sapphire Ring',
    category: 'Jewelry',
    location: 'Showroom Collection',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.50.jpeg',
    description: '18k white gold ring starring a certified royal blue sapphire.',
  },
  {
    id: 15,
    title: 'Alexandrite Color-Change Gem',
    category: 'Gemstones',
    location: 'Sri Lanka',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.51 (1).jpeg',
    description: 'Rare natural alexandrite demonstrating intense red-to-green color shifting.',
  },
  {
    id: 16,
    title: 'JCK Las Vegas Jewellery Expo',
    category: 'Exhibitions',
    location: 'Las Vegas, USA',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.51 (2).jpeg',
    description: 'Exclusive trade presentation for North American jewelry houses.',
  },
  {
    id: 17,
    title: 'Emerald Cut Emerald Ring',
    category: 'Jewelry',
    location: 'Private Order',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.51 (3).jpeg',
    description: 'Vivid green natural emerald flanked by tapered baguette diamonds.',
  },
  {
    id: 18,
    title: 'Star Sapphire Selection',
    category: 'Gemstones',
    location: 'Colombo Vault',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.51.jpeg',
    description: 'Phenomenal star sapphire exhibiting a sharp, well-defined six-ray star.',
  },
  {
    id: 19,
    title: 'Singapore Jewellery Fair',
    category: 'Exhibitions',
    location: 'Marina Bay Sands, Singapore',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.52 (1).jpeg',
    description: 'Annual luxury exposition presented to Southeast Asian collectors.',
  },
  {
    id: 20,
    title: 'Bespoke Gemstone Bracelet',
    category: 'Jewelry',
    location: 'Atelier Vault',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.52 (2).jpeg',
    description: 'Multi-gemstone line bracelet handset in 18k yellow gold.',
  },
  {
    id: 21,
    title: 'Pink Sapphire Oval Cut',
    category: 'Gemstones',
    location: 'Sri Lanka',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.52 (3).jpeg',
    description: 'Vibrant magenta-pink Ceylon sapphire cut with exceptional brilliance.',
  },
  {
    id: 22,
    title: 'Dubai International Jewellery Week',
    category: 'Exhibitions',
    location: 'Dubai World Trade Centre',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.52.jpeg',
    description: 'Middle East VIP salon showcase of bespoke high jewelry creations.',
  },
  {
    id: 23,
    title: 'Art Deco Sapphire Pendant',
    category: 'Jewelry',
    location: 'Heritage Collection',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.53 (1).jpeg',
    description: 'Intricate vintage-inspired pendant set with calibrated sapphires.',
  },
  {
    id: 24,
    title: 'Tsavorite Garnet Parcel',
    category: 'Gemstones',
    location: 'Sri Lanka',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.53 (2).jpeg',
    description: 'Intense forest-green tsavorite garnets ideal for custom suite designs.',
  },
  {
    id: 25,
    title: 'Baselworld Luxury Watch & Gem Show',
    category: 'Exhibitions',
    location: 'Basel, Switzerland',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.53 (3).jpeg',
    description: 'Prestigious global event featuring elite gem cutters and master jewellers.',
  },
  {
    id: 26,
    title: 'Pear Shape Diamond & Gem Cocktail Ring',
    category: 'Jewelry',
    location: 'Signature Line',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.53.jpeg',
    description: 'Dramatic cocktail ring featuring a central pear-shaped gemstone.',
  },
  {
    id: 27,
    title: 'Spinel Gemstones Collection',
    category: 'Gemstones',
    location: 'Colombo Vault',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.54 (1).jpeg',
    description: 'Rare Burmese and Ceylon spinels ranging from vivid cobalt to flame red.',
  },
  {
    id: 28,
    title: 'Munich Mineral & Gem Expo',
    category: 'Exhibitions',
    location: 'Munich, Germany',
    year: '2023',
    image: '/WhatsApp Image 2026-08-11 at 21.01.54 (2).jpeg',
    description: 'Showcasing rare mineral specimens and cut gemstones in Europe.',
  },
  {
    id: 29,
    title: 'Custom Diamond Engagement Ring',
    category: 'Jewelry',
    location: 'Bespoke Order',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.54 (3).jpeg',
    description: 'Timeless solitaire ring setting designed for optimal light reflection.',
  },
  {
    id: 30,
    title: 'Chrysoberyl Cat’s Eye',
    category: 'Gemstones',
    location: 'Sri Lanka',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.54.jpeg',
    description: 'World-renowned honey yellow Ceylon cat’s eye with razor-sharp chatoyancy.',
  },
  {
    id: 31,
    title: 'The Choice Gems Showroom & Gallery',
    category: 'Exhibitions',
    location: 'Colombo 03, Sri Lanka',
    year: '2024',
    image: '/WhatsApp Image 2026-08-11 at 21.01.55.jpeg',
    description: 'Our flagship Colombo gallery and private consulting lounge.',
  },
];
